import Head from 'next/head';

import SwiperContainer from '../components/UIs/swiper/SwiperContainer';
import { Fragment } from 'react';

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>WiZR Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <SwiperContainer />
      </main>

    </Fragment>
  )
}
